spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/futebola
    username: root
    password: root
---
spring:
  devtools:
    livereload:
      enabled: true
  output:
    ansi:
      enabled: always
  main:
    banner-mode: log

logging:
  level:
    sql: DEBUG