spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/futebola
    username: root
    password: root
  cloud:
    openfeign:
      client:
        config:
          rapidapi:
            url: https://footapi7.p.rapidapi.com/api
            defaultRequestHeaders:
              'X-RapidAPI-Key': '67f551b823msh34866d68c74885cp1f1224jsnd7e6dabf5245'
              'X-RapidAPI-Host': 'footapi7.p.rapidapi.com'

logging:
  level:
    # noinspection undefined
    com:
      sevenine:
        futebola:
          evento:
            datasources:
              restapi:
                sofascore:
                  SofaScoreFeignClient: DEBUG
---
# noinspection undefined
app:
  config:
    endpoint:
      sofascore:
        players: ${sofascore.uri}/team/{idTeam}/players

spring:
  devtools:
    livereload:
      enabled: true
  output:
    ansi:
      enabled: always
  main:
    banner-mode: log

logging:
  level:
    sql: DEBUG