spring:
  datasource:
    url: jdbc:mariadb://192.168.49.2:30006/futebola
    username: root
    password: root
  cloud:
    openfeign:
      client:
        config:
          rapidapi:
            url: https://footapi7.p.rapidapi.com/api
            defaultRequestHeaders:
              'X-RapidAPI-Key': '67f551b823msh34866d68c74885cp1f1224jsnd7e6dabf5245'
              'X-RapidAPI-Host': 'footapi7.p.rapidapi.com'

logging:
  level:
    web: DEBUG
    sql: OFF
    # noinspection undefined
    org:
      zalando:
        logbook: DEBUG
    # noinspection undefined
    com:
      sevenine:
        futebola:
          evento:
            adapter:
              endpoints:
                rapidapi: TRACE
# noinspection undefined
app:
  config:
    job:
      codigoAtualizaJogadores: 1ff2df54-caa1-11ed-8305-a251453ec86a
    exception:
      codigoNaoConfigurado:
        codigo: 101
        descricao: Código não cadastrado nas configurações
      foraDoHorarioDeExecucao:
        codigo: 102
        descricao: Fora do horário de execução
      horarioJaExecutado:
        codigo: 103
        descricao: Já ocorreu execução para o horário
---
spring:
  devtools:
    livereload:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS
  main:
    banner-mode: LOG