apiVersion: v1
kind: Service
metadata:
  name: job-futebola-rapidapi
spec:
  type: NodePort
  selector:
    app: job-futebola-rapidapi
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000